parameters:
    env(HUGGINGFACE_API_KEY): ''
    env(HUGGINGFACE_MODEL): ''
    env(HUGGINGFACE_TIMEOUT): ''

services:
    App\Service\HuggingFaceChatbot:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $apiKey: '%env(HUGGINGFACE_API_KEY)%'
            $model: '%env(HUGGINGFACE_MODEL)%'
            $timeout: '%env(int:HUGGINGFACE_TIMEOUT)%'