security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Users: 'auto'

    # User providers configuration
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                # Tu veux utiliser "email" comme identifiant pour te connecter
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\FacebookAuthenticator
                - App\Security\GoogleAuthenticator
        
              # Utilise 'password'

            logout:
                path: app_logout
                target: app_user_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /

    access_control:
        # Configuration des règles d'accès si nécessaire

when@test:
    security:
        password_hashers:
